Flipez/rocket-lang

object/boolean_test.go, object/builtin.go, object/error.go, object/error_test.go, object/function.go, object/function_test.go, object/hash.go, object/integer_test.go, object/null.go, object/null_test.go, object/object.go, object/object_test.go, object/return_value.go, object/return_value_test.go, object/string_test.go
=> cleanup objects

ast/ast.go, docs/content/docs/specification/modules.md, evaluator/evaluator.go, evaluator/evaluator_test.go, fixtures/module.rl, main.go, object/environment.go, object/module.go, object/object.go, object/object_test.go, parser/parser.go, parser/parser_test.go, repl/repl.go, token/token.go, utilities/utilities.go
=> add ability to import modules

ast/ast.go, ast/ast_test.go, docs/content/en/docs/control_expressions/foreach.md, docs/content/en/docs/home.md, docs/content/en/docs/literals/boolean.md, docs/content/en/docs/literals/hash.md, docs/content/en/docs/literals/integer.md, docs/content/en/docs/literals/string.md, docs/content/en/docs/specification/closures.md, docs/content/en/docs/specification/functions.md, docs/content/en/docs/specification/local_variables.md, docs/generate.go, evaluator/evaluator.go, evaluator/evaluator_test.go, examples/aoc/2021/day-1/complete.rl, lexer/lexer_test.go, object/array_test.go, object/hash_test.go, object/string_test.go, parser/parser.go, parser/parser_test.go, token/token.go
=> remove let

ast/ast.go, docs/content/en/docs/control_expressions/if.md, docs/content/en/docs/home.md, docs/content/en/docs/specification/functions.md, evaluator/evaluator.go, evaluator/evaluator_test.go, examples/aoc/2021/day-2/complete.rl, examples/misc/if.rl, parser/parser.go, token/token.go
=> make curly braces optional

lexer/lexer.go, token/token.go
=> clean up lexer

lexer/lexer.go
=> fix comments

docs/content/docs/literals/float.md, docs/content/docs/literals/integer.md, docs/content/docs/literals/null.md, evaluator/foreach.go, examples/aoc/2021/day-1/complete.rl, examples/misc/foreach-error.rl, object/float.go, object/float_test.go, object/integer.go, object/integer_test.go, object/null.go, object/null_test.go
This adds error handling in foreach blocks and adds a few object methods to improve type handling.
This fixes #50
=> Foreach error abort

.goreleaser.yml
=> build more packages

ast/ternary.go, evaluator/evaluator.go, evaluator/evaluator_test.go, evaluator/ternary.go, lexer/lexer.go, parser/parser.go, parser/ternary.go, token/token.go
=> add ternary

ast/ast_test.go, ast/boolean.go, ast/float.go, ast/foreach.go, ast/if.go, ast/integer.go, ast/return.go, ast/string.go
=> add ast tests

docs/blog/authors.yml, docs/blog/releases/2022-07-25-release-0.18.md, docs/docusaurus.config.js
=> add first release post

docs/docusaurus.config.js
=> link playground

docs/docs/language/_category_.yml, docs/docs/language/operators.md, docs/docusaurus.config.js, evaluator/evaluator_test.go, evaluator/infix.go, lexer/lexer.go, lexer/lexer_test.go, parser/parser.go, token/token.go
=> Implement `and`, `or` , `&&` and `||`

docs/src/css/custom.css
=> use inter font

docs/docs/builtins/Time.md, evaluator/evaluator_test.go, stdlib/std.go, stdlib/time.go
=> add Time builtin

ast/import.go, docs/docs/language/modules.md, evaluator/evaluator_test.go, evaluator/import.go, parser/import.go, parser/program.go
=> allow module name to be defined optionally

docs/docs/control_expressions/if.md
This fixes https://github.com/Flipez/rocket-lang/issues/121
=> document else if

stdlib/math.go
=> [stdlib/math] Seed rand on each call

object/hash.go
=> [foreach/hash] Swap key/value order

evaluator/module.go
=> [evaluator/module] fix ioutil deprecation

object/math_test.go, stdlib/math.go
=> [stdlib/math] Add support for Math.round()

main.go, object/file.go, object/http_test.go
=> [mixed] fix ioutil deprecation

docs/docs/builtins/Math.md, docs/docs/literals/array.md, object/array.go, object/array_test.go
=> [object/array] Add ability to .sort()

docs/docs/literals/array.md, object/array.go, object/array_test.go
=> [object/array] Add ability to .reverse()

docs/docs/literals/string.md, object/object.go, object/string.go, object/string_test.go
=> [object/string] Add support for .format()

docs/components/GetStarted.tsx, docs/components/Highlights.js, docs/components/Highlights.module.css, docs/components/get-started.module.css, docs/docs/install.md, docs/package.json, docs/src/css/custom.css, docs/yarn.lock
=> [docs] Update documentation

docs/docs/literals/error.md, docs/generate.go, evaluator/evaluator_test.go, stdlib/raise.go, stdlib/std.go
=> [object/error] Add `raise()` builtin

docs/docs/literals/string.md, object/string.go
=> [object/string] Fix `.find()` and `.count()`  argument validation to only accept STRING

.goreleaser.yml
=> [release/goreleaser] Add tag to archive filename

docs/docs/control_expressions/foreach.md, docs/docs/control_expressions/while.md
=> [foreach/while] Document return value

docs/docs/literals/array.md, object/array.go, object/array_test.go
=> [object/array] Add ability to `.sum()` elements

ast/integer.go, docs/docs/literals/array.md, evaluator/assign.go, evaluator/evaluator_test.go, evaluator/index.go, evaluator/infix.go, object/array.go, object/file.go, object/float.go, object/http.go, object/integer.go, object/integer_test.go, object/object.go, object/object_test.go, object/string.go, parser/integer.go, parser/parser_test.go, stdlib/time.go
=> [core] Refactor `int64` to `int` where possible
